StoryViewsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: StoryViewsTable-${self:custom.stage}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
    StreamSpecification:
      StreamViewType: NEW_IMAGE
